/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package compose

import org.gradle.api.Project
import org.gradle.api.Plugin

class ComposePlugin: Plugin<Project> {
    override fun apply(project: Project) {

    }
}
