/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.marmatsan.dependencies

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings
import org.gradle.api.initialization.resolve.DependencyResolutionManagement

class Dependencies : Plugin<Settings> {
    override fun apply(settings: Settings) {
        settings.dependencyResolutionManagement {

        }
    }
}

private fun DependencyResolutionManagement.buildVersionCatalogs(catalogs: List<Dependency>) {
    versionCatalogs {
        it.create("libs") {

        }
    }
}